=== priyankayadav98/CAT_2/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<em:schema xmlns:em ="http://www.w3.org/2001/XMLSchema">
	<em:element name="CHRIST" type="STUDENTS" />
    <em:complexType name="STUDENTS">
      <em:sequence>
         <em:element name="COMPUTER-SCIENCE" type="cmp" minOccurs="1" maxOccurs="3" />	
      </em:sequence>
    </em:complexType>
    
    <em:complexType name="cmp">
      <em:sequence>
         <em:element name="STUD-NAME" type="em:string" />
         <em:element name="STUD-UNIVERSITY" type="em:string" />
         <em:element name="STUD-PHONE" type="CHECK" />
         <em:element name="STUD-EMAIL" type="emailAddress" />
      </em:sequence>
      
      
      
    </em:complexType>
        
          
           
     <em:simpleType name = "CHECK">
           <em:restriction base ="em:integer">
           <em:minInclusive value="10"></em:minInclusive>
           </em:restriction>
           </em:simpleType>      
           
           
  <em:simpleType name="emailAddress"> 
    <em:restriction base="em:string"> 
      <em:pattern value="[^@]+@[^\.]+\..+"/> 
    </em:restriction> 
    </em:simpleType>
    
  </em:schema>

=== priyankayadav98/CAT_2/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<CHRIST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NewXMLSchema.xsd">
  <COMPUTER-SCIENCE>
    <STUD-NAME>VIKASH</STUD-NAME>
    <STUD-UNIVERSITY>ANNA MALAI</STUD-UNIVERSITY>
    <STUD-PHONE>6389676192</STUD-PHONE>
    <STUD-EMAIL>abcd1@gmail.com</STUD-EMAIL>
  </COMPUTER-SCIENCE>
   <COMPUTER-SCIENCE>
    <STUD-NAME>NIMISHA</STUD-NAME>
    <STUD-UNIVERSITY>SRM UNIVERSITY</STUD-UNIVERSITY>
    <STUD-PHONE>6489676192</STUD-PHONE>
    <STUD-EMAIL>xyz123@gmail.com</STUD-EMAIL>
  </COMPUTER-SCIENCE>
   <COMPUTER-SCIENCE>
    <STUD-NAME>HIMANSHU</STUD-NAME>
    <STUD-UNIVERSITY>WAI UNIVERSITY</STUD-UNIVERSITY>
    <STUD-PHONE>6789676192</STUD-PHONE>
    <STUD-EMAIL>weing234@gmail.com</STUD-EMAIL>
  </COMPUTER-SCIENCE>
</CHRIST>
